### ISSUE TITLE
When merging configurations array elements comparison function is shallow 

### ISSUE THREAD

**Issue by kgenge** [KrysKruk/serverless-import-config-plugin#8]
Hi there !
Thank you for supporting the plugin it's really great. 
Unfortunately currently I have an issue with merging configuration fragments that contain elements in array which are objects. Take the 2 logically identical fragments for merging:

``` fragment 1
- DomainName:
    'Fn::Join':
        - ''
        - - Ref: componentsBucket
           - '.s3.${opt:region,self:provider.region}.amazonaws.com'
```

``` fragment 2
- DomainName:
    'Fn::Join':
        - ''
        - - Ref: componentsBucket
           - '.s3.${opt:region,self:provider.region}.amazonaws.com'
```

Due to the fact that uniqueness of the array elements is shallow the {Ref: componentsBucket} element will be added to the merged array which is not what we expect.  current code in merge.ts:10 :
```
if (Array.isArray(target) && Array.isArray(source)) {
    // add unique elements of source into target
    return target.concat(source.filter(elem => !target.includes(elem)))
  }
```
To make it work not only for string elements you could consider using lodash differenceWith and isEqual functions to perform a deep array elements comparison. proposed solution:
``` 
if (Array.isArray(target) && Array.isArray(source)) {
    // add unique elements of source into target with deep elements equality comparison
    return target.concat(differenceWith(source, target, isEqual));
  }
```

If you agree with the proposed solution, could you kindly accept [the PR](https://github.com/KrysKruk/serverless-import-config-plugin/pull/9) and publish a new version to npm repository?

**Comment by KrysKruk** [comment]
Sorry for the late answer. The PR has been merged.
I will publish new version right now.
Thank you very much for this change!
